### ISSUE TITLE
不支持对0开头的数字的格式化操作

### ISSUE THREAD

**Issue by SimbolZhang** [csfuwwc/NSNumberFormatterTest#1]
不支持对0开头的数字的格式化操作
ps：虽然手机号和银行卡号不会以0开头，但是输入的时候感觉有点奇怪

**Comment by csfuwwc** [comment]
因为最后要转成number类型。。内容为01的字符串儿最后成了1。。

**Comment by csfuwwc** [comment]
> 不支持对0开头的数字的格式化操作
> ps：虽然手机号和银行卡号不会以0开头，但是输入的时候感觉有点奇怪

最新版本支持了0开头，业务中遇到了0开头的银行卡号，被实锤了！！！
