### ISSUE TITLE
银行卡号输入不准确

### ISSUE THREAD

**Issue by QingYan-iOS** [csfuwwc/NSNumberFormatterTest#2]
银行卡号 输入倒数第三位的时候 显示的跟输入的不一致

**Comment by csfuwwc** [comment]
已复现。马上修复

**Comment by csfuwwc** [comment]
已上线。

**Comment by csfuwwc** [comment]
问题已修复。


🙏


原始邮件
发件人:阿里看大门的notifications@github.com
收件人:csfuwwc/NSNumberFormatterTestNSNumberFormatterTest@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年9月5日(周三) 11:33
主题:[csfuwwc/NSNumberFormatterTest] 银行卡号输入不准确 (#2)


银行卡号 输入倒数第三位的时候 显示的跟输入的不一致
